platform: linux

image_resource:
  type: docker-image
  source: { repository: alpine }

inputs:
  - name: cardid-src
  - name: cardid-data

outputs:
  - name: cardid-src

run:
  path: ash
  args:
    - -c
    - |
      set -o errexit -o xtrace
      mkdir -p cardid-src/data
      cp -r cardid-data/* cardid-src/data/
