platform: linux

image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: latest

inputs:
- name: manifests

params:
  KUBERNETES_SERVICE_ACCOUNT: ((namespace-deployer))
  KUBERNETES_TOKEN: ((namespace-deployer.token))
  KUBERNETES_API: kubernetes.default.svc
  RELEASE_NAMESPACE: ((namespace-deployer.namespace))
  RELEASE_NAME: ((release_name))

run:
  path: /bin/bash
  args:
  - -c
  - |
    set -o errexit -o nounset -o pipefail

    setup-kube-deployer

    echo "applying chart to ${RELEASE_NAMESPACE} namespace..."
    kapp deploy \
      -y \
      --namespace "${RELEASE_NAMESPACE}" \
      --allow-ns "${RELEASE_NAMESPACE}" \
      --app "${RELEASE_NAME}" \
      --diff-changes \
      -f ./manifests/
