platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 8-alpine

inputs:
  - name: src

run:
  path: ash
  dir: src
  args:
    - -c
    - |
      set -o errexit -o nounset -o pipefail

      node --version
      npm --version

      apk update
      apk upgrade
      apk add --update bash ruby

      npm install
      export LD_LIBRARY_PATH=$PWD/node_modules/appmetrics

      npm run compile
      npm run lint
      npm test -- --forbid-only --forbid-pending
