# Task to generate Docker-compatible labels.json from repo data

platform: linux

image_resource:
  type: docker-image
  source: { repository: alpine }

inputs:
  - name: repo

outputs:
  - name: labels

run:
  path: ash
  args:
    - -c
    - |
      set -o errexit -o nounset
      short_ref=$(cat repo/.git/short_ref)
      tee labels/labels.json <<EOF
      {
        "commit": "$short_ref"
      }
      EOF
