# Concourse task to package a set of Helm charts

platform: linux

image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: latest

inputs:
- name: pay-gsp

outputs:
- name: chart-package
- name: chart-version

params:
  CHART_NAME: ((chart_name))
  CLUSTER_NAME: ((cluster.name))
  CLUSTER_DOMAIN: ((cluster.domain))
  CLUSTER_PRIVATE_KEY: ((cluster.privateKey))
  RELEASE_NAMESPACE: ((namespace-deployer.namespace))

run:
  path: /bin/bash
  args:
  - -xc
  - |
    set -o errexit -o nounset -o pipefail

    echo "preparing keyring..."
    echo "${CLUSTER_PRIVATE_KEY}" > key
    gpg --import key
    gpg --export-secret-keys > ~/.gnupg/pubring.gpg
    KEY_ID="$(gpg --list-secret-keys --with-colons  | awk -F: '/uid:/ {print $10}' | head -n1)"

    TIMESTAMP=$(date +'%Y%m%d.%H%M')
    APP_VERSION=$(git -C pay-gsp rev-parse --short HEAD)
    CHART_VERSION="1.0.0-$TIMESTAMP-$APP_VERSION"

    echo "$CHART_NAME" > chart-version/name
    echo "$CHART_VERSION" > chart-version/tag

    echo "generating signed (${KEY_ID}) helm package for ${CHART_NAME} at app-version: '${APP_VERSION}' chart-version: '${CHART_VERSION}'..."
    helm package \
      --app-version "${APP_VERSION}" \
      --version "${CHART_VERSION}" \
      --destination "./chart-package/" \
      --save=false \
      --sign \
      --key "${KEY_ID}" \
      "./pay-gsp/charts/${CHART_NAME}"
