platform: linux

image_resource:
  type: docker-image
  source: { repository: alpine }

outputs:
  - name: values

run:
  path: ash
  args:
    - -c
    - |
      set -o errexit -o xtrace
      cat > values/db.yaml <<EOF
      db:
        host: stubs-postgresql.portfolio-pay-stubs.svc
        password: mysecretpassword
      EOF
