platform: linux

image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: latest

inputs:
  - name: src
  - name: endtoend-image
  - name: stubs-image
  - name: demo-service-image

outputs:
  - name: src

run:
  path: bash
  args:
    - -xc
    - |
      set -o errexit -o nounset -o pipefail

      ref() {
        jq -r '.[0].Config.Labels.commit' < "$1/docker_inspect.json"
      }

      cat > new_values.yaml <<EOF
      endtoend:
        image:
          tag: $(ref endtoend-image)
      demoService:
        image:
          tag: $(ref demo-service-image)
      stubs:
        image:
          tag: $(ref stubs-image)
      EOF

      spruce merge src/charts/stubs/values.yaml new_values.yaml > tmp
      tee src/charts/stubs/values.yaml < tmp
