platform: linux

image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: latest

inputs:
  - name: src
  - name: adminusers-image
  - name: cardid-image
  - name: connector-image
  - name: demo-service-image
  - name: dd-connector-image
  - name: dd-frontend-image
  - name: endtoend-image
  - name: frontend-image
  - name: ledger-image
  - name: products-image
  - name: products-ui-image
  - name: publicapi-image
  - name: publicauth-image
  - name: selfservice-image
  - name: stubs-image
  - name: toolbox-image

outputs:
  - name: src

run:
  path: bash
  args:
    - -xc
    - |
      set -o errexit -o nounset -o pipefail

      cat > new_values.yaml <<EOF
      adminUsers:
        image:
          repository: $(cat adminusers-image/repository)
          tag: $(cat adminusers-image/tag)
      cardID:
        image:
          repository: $(cat cardid-image/repository)
          tag: $(cat cardid-image/tag)
      connector:
        image:
          repository: $(cat connector-image/repository)
          tag: $(cat connector-image/tag)
      directDebit:
        connector:
          image:
            repository: $(cat dd-connector-image/repository)
            tag: $(cat dd-connector-image/tag)
        frontend:
          host:
          image:
            repository: $(cat dd-frontend-image/repository)
            tag: $(cat dd-frontend-image/tag)
      frontend:
        host:
        image:
          repository: $(cat frontend-image/repository)
          tag: $(cat frontend-image/tag)
      products:
        image:
          repository: $(cat products-image/repository)
          tag: $(cat products-image/tag)
        ui:
          host:
          image:
            repository: $(cat products-ui-image/repository)
            tag: $(cat products-ui-image/tag)
      public:
        api:
          image:
            repository: $(cat publicapi-image/repository)
            tag: $(cat publicapi-image/tag)
        auth:
          image:
            repository: $(cat publicauth-image/repository)
            tag: $(cat publicauth-image/tag)
      selfService:
        image:
          repository: $(cat selfservice-image/repository)
          tag: $(cat selfservice-image/tag)
      EOF

      spruce merge src/charts/pay/values.yaml new_values.yaml > tmp
      mv tmp src/charts/pay/values.yaml
