platform: linux

image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: latest

inputs:
  - name: src
  - name: endtoend-image
  - name: stubs-image
  - name: demo-service-image

outputs:
  - name: src

run:
  path: bash
  args:
    - -xc
    - |
      set -o errexit -o nounset -o pipefail

      cat > new_values.yaml <<EOF
      endtoend:
        image:
          tag: $(cat endtoend-image/tag)
      demoService:
        image:
          tag: $(cat demo-service-image/tag)
      stubs:
        image:
          tag: $(cat stubs-image/tag)
      EOF

      spruce merge src/charts/stubs/values.yaml new_values.yaml > tmp
      mv tmp src/charts/stubs/values.yaml
