platform: linux

image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: latest

inputs:
  - name: src
  - name: adminusers-image
  - name: cardid-image
  - name: connector-image
  - name: dd-connector-image
  - name: dd-frontend-image
  - name: frontend-image
  - name: ledger-image
  - name: products-image
  - name: products-ui-image
  - name: publicapi-image
  - name: publicauth-image
  - name: selfservice-image
  - name: toolbox-image

outputs:
  - name: src

run:
  path: bash
  args:
    - -xc
    - |
      set -o errexit -o nounset -o pipefail

      ref() {
        jq -r '.[0].Config.Labels.commit' < "$1/docker_inspect.json"
      }

      cat > new_values.yaml <<EOF
      adminUsers:
        image:
          repository: $(cat adminusers-image/repository)
          tag: $(ref adminusers-image)
      cardID:
        image:
          repository: $(cat cardid-image/repository)
          tag: $(ref cardid-image)
      connector:
        image:
          repository: $(cat connector-image/repository)
          tag: $(ref connector-image)
      directDebit:
        connector:
          image:
            repository: $(cat dd-connector-image/repository)
            tag: $(ref dd-connector-image)
        frontend:
          host:
          image:
            repository: $(cat dd-frontend-image/repository)
            tag: $(ref dd-frontend-image)
      frontend:
        host:
        image:
          repository: $(cat frontend-image/repository)
          tag: $(ref frontend-image)
      products:
        image:
          repository: $(cat products-image/repository)
          tag: $(ref products-image)
        ui:
          host:
          image:
            repository: $(cat products-ui-image/repository)
            tag: $(ref products-ui-image)
      public:
        api:
          image:
            repository: $(cat publicapi-image/repository)
            tag: $(ref publicapi-image)
        auth:
          image:
            repository: $(cat publicauth-image/repository)
            tag: $(ref publicauth-image)
      selfService:
        image:
          repository: $(cat selfservice-image/repository)
          tag: $(ref selfservice-image)
      EOF

      spruce merge src/charts/pay/values.yaml new_values.yaml > tmp
      tee src/charts/pay/values.yaml < tmp
