---
applications:
  - name: card-id
    health-check-type: process
    memory: 1G
    env:
      ADMIN_PORT: '9801'
      RUN_APP: 'true'
      DISABLE_INTERNAL_HTTPS: 'true'
      JAVA_OPTS: -Xms512m -Xmx1G
      AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
    routes:
    - route: pay-card-id-((developer)).london.cloudapps.digital
    - route: card-id.apps.internal
