---
applications:
  - name: chrome
    health-check-type: process
    memory: 2G
    env:
      HUB_HOST: selenium-hub.apps.internal
      HUB_PORT: 4444
      NODE_MAX_INSTANCES: 4
      NODE_MAX_SESSION: 4
    routes:
    - route: chrome.apps.internal
