---
applications:
  - name: connector
    db: true
    sqs: true
    docker:
      image: govukpay/connector:latest-master
      username: govukpaypaas
    health-check-type: process
    memory: 1G
    env:
      ADMIN_PORT: '9301'
      DB_HOST: pay-db-((developer)).apps.internal
      DB_SSL_OPTION: ssl=false
      DB_USER: connector
      DB_PASSWORD: mysecretpassword
      FRONTEND_URL: https://pay-frontend-((developer)).london.cloudapps.digital
      SECURE_WORLDPAY_NOTIFICATION_ENABLED: 'false'
      SECURE_WORLDPAY_NOTIFICATION_DOMAIN: london.cloudapps.digital
      GDS_CONNECTOR_WORLDPAY_URL: https://pay-stubs-((developer)).london.cloudapps.digital/stub/worldpay
      GDS_CONNECTOR_WORLDPAY_TEST_URL: https://pay-stubs-((developer)).london.cloudapps.digital/stub/worldpay
      GDS_CONNECTOR_WORLDPAY_LIVE_URL: https://pay-stubs-((developer)).london.cloudapps.digital/stub/worldpay
      APPLE_PAY_PAYMENT_PROCESSING_PRIVATE_KEY: MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgOqukXQoQVbg1xvvq/IGLdK0UuJPbbawULTALcuw/Uz2hRANCAAQPjiA1kTEodST2wy5d5kQFrM0D5qBX9Ukry8W6D+vC7OqbMoTm/upRM1GRHeA2LaVTrwAnpGhoO0ETqYF2Nu4V
      APPLE_PAY_PAYMENT_PROCESSING_CERTIFICATE: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVjRENDQkJhZ0F3SUJBZ0lJVXlyRU00SXpCSFF3Q2dZSUtvWkl6ajBFQXdJd2dZQXhOREF5QmdOVkJBTU0KSzBGd2NHeGxJRmR2Y214a2QybGtaU0JFWlhabGJHOXdaWElnVW1Wc1lYUnBiMjV6SUVOQklDMGdSekl4SmpBawpCZ05WQkFzTUhVRndjR3hsSUVObGNuUnBabWxqWVhScGIyNGdRWFYwYUc5eWFYUjVNUk13RVFZRFZRUUtEQXBCCmNIQnNaU0JKYm1NdU1Rc3dDUVlEVlFRR0V3SlZVekFlRncweE5ERXdNall4TWpFd01UQmFGdzB4TmpFeE1qUXgKTWpFd01UQmFNSUdoTVM0d0xBWUtDWkltaVpQeUxHUUJBUXdlYldWeVkyaGhiblF1WTI5dExuTmxZWFJuWldWcgpMbE5sWVhSSFpXVnJNVFF3TWdZRFZRUUREQ3ROWlhKamFHRnVkQ0JKUkRvZ2JXVnlZMmhoYm5RdVkyOXRMbk5sCllYUm5aV1ZyTGxObFlYUkhaV1ZyTVJNd0VRWURWUVFMREFvNVFqTlJXVGxYUWxvMU1SY3dGUVlEVlFRS0RBNVQKWldGMFIyVmxheXdnU1c1akxqRUxNQWtHQTFVRUJoTUNWVk13V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQgpCd05DQUFRUGppQTFrVEVvZFNUMnd5NWQ1a1FGck0wRDVxQlg5VWtyeThXNkQrdkM3T3FiTW9UbS91cFJNMUdSCkhlQTJMYVZUcndBbnBHaG9PMEVUcVlGMk51NFZvNElDVlRDQ0FsRXdSd1lJS3dZQkJRVUhBUUVFT3pBNU1EY0cKQ0NzR0FRVUZCekFCaGl0b2RIUndPaTh2YjJOemNDNWhjSEJzWlM1amIyMHZiMk56Y0RBMExXRndjR3hsZDNkawpjbU5oTWpBeE1CMEdBMVVkRGdRV0JCUVdHZktnUGdWQlg4Sk92ODRxMWMwNEhTaE1tekFNQmdOVkhSTUJBZjhFCkFqQUFNQjhHQTFVZEl3UVlNQmFBRklTMmhNdzZobUp5RmxtVTZCcWp2VWpmT3Q4TE1JSUJIUVlEVlIwZ0JJSUIKRkRDQ0FSQXdnZ0VNQmdrcWhraUc5Mk5rQlFFd2dmNHdnY01HQ0NzR0FRVUZCd0lDTUlHMkRJR3pVbVZzYVdGdQpZMlVnYjI0Z2RHaHBjeUJqWlhKMGFXWnBZMkYwWlNCaWVTQmhibmtnY0dGeWRIa2dZWE56ZFcxbGN5QmhZMk5sCmNIUmhibU5sSUc5bUlIUm9aU0IwYUdWdUlHRndjR3hwWTJGaWJHVWdjM1JoYm1SaGNtUWdkR1Z5YlhNZ1lXNWsKSUdOdmJtUnBkR2x2Ym5NZ2IyWWdkWE5sTENCalpYSjBhV1pwWTJGMFpTQndiMnhwWTNrZ1lXNWtJR05sY25ScApabWxqWVhScGIyNGdjSEpoWTNScFkyVWdjM1JoZEdWdFpXNTBjeTR3TmdZSUt3WUJCUVVIQWdFV0ttaDBkSEE2Ckx5OTNkM2N1WVhCd2JHVXVZMjl0TDJObGNuUnBabWxqWVhSbFlYVjBhRzl5YVhSNUx6QTJCZ05WSFI4RUx6QXQKTUN1Z0thQW5oaVZvZEhSd09pOHZZM0pzTG1Gd2NHeGxMbU52YlM5aGNIQnNaWGQzWkhKallUSXVZM0pzTUE0RwpBMVVkRHdFQi93UUVBd0lES0RCUEJna3Foa2lHOTJOa0JpQUVRZ3hBUmprek9FWTBOalU0UTBFeVF6RkRPVU16Ck9FSTRSRVpEUWpWRVFrSXlRVEl5TkRVMk1EZEVSRVV5UmpFeE5EWXlNRVU0TkRZNFJVWTFNa1F5TURoRFFUQUsKQmdncWhrak9QUVFEQWdOSUFEQkZBaUIrUTR6enBNajJESlRDSWhERkJjbXdLMXpRQUM3MGZZMklzWWQ4K054dQp1d0loQUtqOVJyVE95aWFRbm9UNU1xaTNVSG9wYjZ4VHVnbDNMVURCbG9yYUJIeVAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
      GDS_CONNECTOR_SMARTPAY_URL: https://pay-stubs-((developer)).london.cloudapps.digital/stub/smartpay
      GDS_CONNECTOR_SMARTPAY_TEST_URL: https://pay-stubs-((developer)).london.cloudapps.digital/stub/smartpay
      GDS_CONNECTOR_SMARTPAY_LIVE_URL: https://pay-stubs-((developer)).london.cloudapps.digital/stub/smartpay
      GDS_CONNECTOR_EPDQ_TEST_URL: https://pay-stubs-((developer)).london.cloudapps.digital/stub/epdq
      GDS_CONNECTOR_EPDQ_LIVE_URL: https://pay-stubs-((developer)).london.cloudapps.digital/stub/epdq
      GDS_CONNECTOR_SMARTPAY_NOTIFICATION_USER: smartpay-user
      GDS_CONNECTOR_SMARTPAY_NOTIFICATION_PASSWORD: smartpay-password
      STRIPE_TRANSACTION_FEE_PERCENTAGE: '0.1'
      JPA_LOG_LEVEL: WARNING
      JPA_SQL_LOG_LEVEL: WARNING
      HTTP_PROXY_ENABLED: 'false'
      HTTP_PROXY_HOST: pay-egress-((developer)).apps.internal
      HTTP_PROXY_PORT: '8080'
      HTTP_PROXY_SCHEME: http
      AUTH_READ_TIMEOUT_SECONDS: '1'
      NOTIFY_EMAIL_ENABLED: 'true'
      NOTIFY_PAYMENT_RECEIPT_EMAIL_TEMPLATE_ID: email-template-id
      NOTIFY_REFUND_ISSUED_EMAIL_TEMPLATE_ID: email-refund-issued-template-id
      NOTIFY_API_KEY: api_key-pay-notify-service-id-pay-notify-secret-needs-to-be-32-chars-fsghdngfhmhfkrgsfs
      NOTIFY_BASE_URL: https://pay-stubs-((developer)).london.cloudapps.digital/notify
      CAPTURE_PROCESS_SCHEDULER_INITIAL_DELAY_SECONDS: '0'
      CAPTURE_PROCESS_SCHEDULER_RANDOM_INTERVAL_MINIMUM_SECONDS: '1'
      CAPTURE_PROCESS_SCHEDULER_RANDOM_INTERVAL_MAXIMUM_SECONDS: '1'
      XRAY_ENABLED: false
      CAPTURE_USING_SQS_FEATURE_FLAG: 'true'
      AWS_SQS_REGION: region-1
      AWS_SQS_CAPTURE_QUEUE_URL: http://pay-sqs-((developer)).apps.internal:9324/queue/pay_capture_queue
      AWS_SECRET_KEY: x
      AWS_ACCESS_KEY: x
      AWS_SQS_NON_STANDARD_SERVICE_ENDPOINT: 'true'
      AWS_SQS_ENDPOINT: http://pay-sqs-((developer)).apps.internal:9324
      AWS_SQS_MESSAGE_MAXIMUM_WAIT_TIME_IN_SECONDS: '20'
      EVENT_QUEUE_ENABLED: 'true'
      AWS_SQS_PAYMENT_EVENT_QUEUE_URL: http://pay-sqs-((developer)).apps.internal:9324/queue/pay_event_queue
      RUN_MIGRATION: 'true'
      RUN_APP: 'true'
      DISABLE_INTERNAL_HTTPS: 'true'
      JAVA_OPTS: -Xms512m -Xmx1G
    routes:
    - route: pay-connector-((developer)).london.cloudapps.digital
    - route: pay-connector-((developer)).apps.internal
