---
applications:
  - name: ledger
    health-check-type: process
    memory: 1G
    env:
      ADMIN_PORT: '10701'
      DB_HOST: postgres.apps.internal
      DB_SSL_OPTION: ssl=false
      DB_USER: ledger
      DB_PASSWORD: mysecretpassword
      AWS_SQS_REGION: region-1
      AWS_SECRET_KEY: x
      AWS_ACCESS_KEY: x
      AWS_SQS_NON_STANDARD_SERVICE_ENDPOINT: 'true'
      AWS_SQS_ENDPOINT: http://sqs.apps.internal:9324
      AWS_SQS_MESSAGE_MAXIMUM_WAIT_TIME_IN_SECONDS: '20'
      QUEUE_MESSAGE_RECEIVER_THREAD_DELAY_IN_MILLISECONDS: '1000'
      AWS_SQS_PAYMENT_EVENT_QUEUE_URL: http://sqs.apps.internal:9324/queue/pay_event_queue
      RUN_MIGRATION: 'true'
      RUN_APP: 'true'
      DISABLE_INTERNAL_HTTPS: 'true'
      JAVA_OPTS: -Xms512m -Xmx1G
      AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
    routes:
    - route: pay-ledger-((developer)).london.cloudapps.digital
