---
applications:
  - name: stubs
    docker:
      image: govukpay/stubs:latest-master
      username: govukpaypaas
    health-check-type: process
    memory: 1G
    env:
      SMARTPAY_EXPECTED_USER: smartpay-user
      SMARTPAY_EXPECTED_PASSWORD: smartpay-password
      WORLDPAY_EXPECTED_USER: worldpay-user
      WORLDPAY_EXPECTED_PASSWORD: worldpay-password
      CONNECTOR_SANDBOX_NOTIFICATION_URL: https://pay-connector-((developer)).london.cloudapps.digital/v1/api/notifications/sandbox
      CONNECTOR_WORLDPAY_NOTIFICATION_URL: https://pay-connector-((developer)).london.cloudapps.digital/v1/api/notifications/worldpay
      CONNECTOR_SMARTPAY_NOTIFICATION_URL: https://pay-connector-((developer)).london.cloudapps.digital/v1/api/notifications/smartpay
      CONNECTOR_EPDQ_NOTIFICATION_URL: https://pay-connector-((developer)).london.cloudapps.digital/v1/api/notifications/epdq
      CONNECTOR_DIRECT_DEBIT_SANDBOX_NOTIFICATION_URL: https://directdebit-connector.london.cloudapps.digital/v1/webhooks/sandbox
      CONNECTOR_DIRECT_DEBIT_GOCARDLESS_NOTIFICATION_URL: https://directdebit-connector.london.cloudapps.digital/v1/webhooks/gocardless
      CONNECTOR_DIRECT_DEBIT_GOCARDLESS_WEBHOOK_SECRET: supersecret
      EPDQ_SHA_OUT_PASSPHRASE: mysecretpassphrase
      EXTERNAL_STUBS_URL: https://pay-stubs-((developer)).london.cloudapps.digital/
      FRONTEND_URL: https://pay-frontend-((developer)).london.cloudapps.digital
    routes:
    - route: pay-stubs-((developer)).london.cloudapps.digital
