---
apiVersion: concourse.k8s.io/v1beta1
kind: Pipeline
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: build-release
spec:
  exposed: true
  pipelineString: |

    harbor_source: &harbor_source
      username: ((harbor.harbor_username))
      password: ((harbor.harbor_password))
      harbor:
        url: ((harbor.harbor_url))
        prevent_vul: "false"
      notary:
        url: ((harbor.notary_url))
        root_key: ((harbor.root_key))
        delegate_key: ((harbor.ci_key))
        passphrase:
          root: ((harbor.notary_root_passphrase))
          snapshot: ((harbor.notary_snapshot_passphrase))
          targets: ((harbor.notary_targets_passphrase))
          delegation: ((harbor.notary_delegation_passphrase))

    resource_types:
      - name: github
        type: registry-image
        source:
          repository: govsvc/concourse-github-resource
          tag: "gsp-v1.1.31"

      - name: harbor
        type: registry-image
        privileged: true
        source:
          repository: govsvc/concourse-harbor-resource
          tag: "gsp-v1.1.31"

    resources:
      - name: pipelines
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-gsp-pipelines
          branch: master
          username: re-autom8-ci
          password: ((github.api-token))

      - name: deployment
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-deployment
          branch: develop
          username: re-autom8-ci
          password: ((github.api-token))

      - name: pay-cardid-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-cardid
          branch: master

      - name: pay-cardid-data
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-cardid-data
          username: re-autom8-ci
          password: ((github.api-token))

      - name: pay-cardid-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/cardid

      - name: pay-frontend-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-frontend
          branch: master

      - name: pay-frontend-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/frontend

      - name: pay-toolbox-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-toolbox
          branch: master

      - name: pay-toolbox-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/toolbox

      - name: pay-adminusers-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-adminusers
          branch: master

      - name: pay-adminusers-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/adminusers

      - name: pay-connector-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-connector
          branch: master

      - name: pay-connector-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/connector

      - name: pay-ledger-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-ledger
          branch: master

      - name: pay-ledger-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/ledger

      - name: pay-products-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-products
          branch: master

      - name: pay-products-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/products

      - name: pay-products-ui-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-products-ui
          branch: master

      - name: pay-products-ui-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/products-ui

      - name: pay-selfservice-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-selfservice
          branch: master

      - name: pay-selfservice-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/selfservice

      - name: pay-publicauth-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-publicauth
          branch: master

      - name: pay-publicauth-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/publicauth

      - name: pay-publicapi-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-publicapi
          branch: master

      - name: pay-publicapi-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/publicapi

      - name: pay-direct-debit-connector-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-direct-debit-connector
          branch: master

      - name: pay-direct-debit-connector-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/direct-debit-connector

      - name: pay-direct-debit-frontend-src
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-direct-debit-frontend
          branch: master

      - name: pay-direct-debit-frontend-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/direct-debit-frontend

      - name: pay-scripts
        type: git
        icon: github-circle
        source:
          uri: https://github.com/alphagov/pay-scripts
          branch: master
          username: re-autom8-ci
          password: ((github.api-token))

      - name: pay-postgresql-image
        type: harbor
        icon: docker
        source:
          <<: *harbor_source
          repository: registry.((cluster.domain))/pay/postgresql

          #- name: pay-endtoend-src
          #  type: git
          #  icon: github-circle
          #  source:
          #    uri: https://github.com/alphagov/pay-endtoend
          #    branch: master


    jobs:
      - name: build-cardid
        plan:
        - get: pipelines
        - get: pay-cardid-src
          trigger: true
          params:
            submodules: none
        - get: pay-cardid-data
          trigger: true
        - task: copy-cardid-data
          file: pipelines/tasks/copy-cardid-data.yaml
        - task: build
          file: pipelines/tasks/maven-build.yaml
          input_mapping: { src: pay-cardid-src }
        - put: pay-cardid-image
          params:
            build: src
            tag_as_latest: true

      - name: build-frontend
        plan:
        - get: pipelines
        - get: pay-frontend-src
          trigger: true
        - task: test
          file: pipelines/tasks/frontend.yaml
          input_mapping: { src: pay-frontend-src }
        - put: pay-frontend-image
          params:
            build: src
            tag_as_latest: true

      - name: build-toolbox
        plan:
        - get: pipelines
        - get: pay-toolbox-src
          trigger: true
        - task: env-file
          config:
            platform: linux
            image_resource:
              type: docker-image
              source: { repository: node }
            inputs:
              - name: pay-toolbox-src
            outputs:
              - name: pay-toolbox-src
            run:
              path: bash
              dir: pay-toolbox-src
              args: [ "./scripts/generate-dev-environment" ]
        - task: test
          file: pipelines/tasks/node-test.yaml
          input_mapping: { src: pay-toolbox-src }
        - put: pay-toolbox-image
          params:
            build: src
            tag_as_latest: true

      - name: build-adminusers
        plan:
        - get: pipelines
        - get: pay-adminusers-src
          trigger: true
        - task: build
          file: pipelines/tasks/maven-build.yaml
          input_mapping: { src: pay-adminusers-src }
        - put: pay-adminusers-image
          params:
            build: src
            tag_as_latest: true

      - name: build-connector
        plan:
        - get: pipelines
        - get: pay-connector-src
          trigger: true
        - task: build
          file: pipelines/tasks/maven-build.yaml
          input_mapping: { src: pay-connector-src }
        - put: pay-connector-image
          params:
            build: src
            tag_as_latest: true

      - name: build-ledger
        plan:
        - get: pipelines
        - get: pay-ledger-src
          trigger: true
        - task: build
          file: pipelines/tasks/maven-build.yaml
          input_mapping: { src: pay-ledger-src }
        - put: pay-ledger-image
          params:
            build: src
            tag_as_latest: true

      - name: build-products
        plan:
        - get: pipelines
        - get: pay-products-src
          trigger: true
        - task: build
          file: pipelines/tasks/maven-build.yaml
          input_mapping: { src: pay-products-src }
        - put: pay-products-image
          params:
            build: src
            tag_as_latest: true

      - name: build-products-ui
        plan:
        - get: pipelines
        - get: pay-products-ui-src
          trigger: true
        - task: test
          file: pipelines/tasks/frontend.yaml
          input_mapping: { src: pay-products-ui-src }
        - put: pay-products-ui-image
          params:
            build: src
            tag_as_latest: true

      - name: build-selfservice
        plan:
        - get: pipelines
        - get: pay-selfservice-src
          trigger: true
        - task: test
          file: pipelines/tasks/frontend.yaml
          input_mapping: { src: pay-selfservice-src }
        - put: pay-selfservice-image
          params:
            build: src
            tag_as_latest: true

      - name: build-publicauth
        plan:
        - get: pipelines
        - get: pay-publicauth-src
          trigger: true
        - task: build
          file: pipelines/tasks/maven-build.yaml
          input_mapping: { src: pay-publicauth-src }
        - put: pay-publicauth-image
          params:
            build: src
            tag_as_latest: true

      - name: build-publicapi
        plan:
        - get: pipelines
        - get: pay-publicapi-src
          trigger: true
        - task: build
          file: pipelines/tasks/maven-build.yaml
          input_mapping: { src: pay-publicapi-src }
        - put: pay-publicapi-image
          params:
            build: src
            tag_as_latest: true

      - name: build-direct-debit-connector
        plan:
        - get: pipelines
        - get: pay-direct-debit-connector-src
          trigger: true
        - task: build
          file: pipelines/tasks/maven-build.yaml
          input_mapping: { src: pay-direct-debit-connector-src }
        - put: pay-direct-debit-connector-image
          params:
            build: src
            tag_as_latest: true

      - name: build-direct-debit-frontend
        plan:
        - get: pipelines
        - get: pay-direct-debit-frontend-src
          trigger: true
        - task: test
          file: pipelines/tasks/frontend.yaml
          input_mapping: { src: pay-direct-debit-frontend-src }
        - put: pay-direct-debit-frontend-image
          params:
            build: src
            tag_as_latest: true

      - name: build-postgresql
        plan:
        - get: pay-scripts
          trigger: true
        - put: pay-postgresql-image
          params:
            build: pay-scripts/images/posgres
            tag_as_latest: true

      - name: deploy-staging
        plan:
        - get: pay-cardid-image
          passed: [ build-cardid ]
        - get: pay-frontend-image
          passed: [ build-frontend ]
        - get: pay-toolbox-image
          passed: [ build-toolbox ]
        - get: pay-adminusers-image
          passed: [ build-adminusers ]
        - get: pay-connector-image
          passed: [ build-connector ]
        - get: pay-ledger-image
          passed: [ build-ledger ]
        - get: pay-products-image
          passed: [ build-products ]
        - get: pay-products-ui-image
          passed: [ build-products-ui ]
        - get: pay-selfservice-image
          passed: [ build-selfservice ]
        - get: pay-publicauth-image
          passed: [ build-publicauth ]
        - get: pay-publicapi-image
          passed: [ build-publicapi ]
        - get: pay-direct-debit-connector-image
          passed: [ build-direct-debit-connector ]
        - get: pay-direct-debit-frontend-image
          passed: [ build-direct-debit-frontend ]
        - get: pay-postgresql-image
          passed: [ build-postgresql ]
        - get: deployment
          trigger: true
        - task: render-manifests
          file: deployment/ci/tasks/render.yaml
          vars:
            environment: staging
        - task: deploy-manifests
          file: deployment/ci/tasks/deploy.yaml
          vars:
            environment: staging

          #- name: test-in-staging
          #  serial: true
          #  plan:
          #  - get: every-10m
          #    trigger: true
          #  - get: pay-endtoend-src

          #  - aggregate:
          #    - task: run-card-tests
          #      file: pay-endtoend-src/ci/tasks/run-tests.yml
          #      input_mapping: { repo: pay-endtoend-src }
          #      params:
          #        TEST_PROFILE: end2end
          #        EXTRA_MVN_ARGS: "-Dit.test=!uk.gov.pay.endtoend.tests.publicapi.PaymentAndRefundIT"

          #    - task: run-directdebit-tests
          #      file: pay-endtoend-src/ci/tasks/run-tests.yml
          #      input_mapping: { repo: pay-endtoend-src }
          #      params:
          #        TEST_PROFILE: end2end-tagged
          #        GROUPS: uk.gov.pay.endtoend.categories.End2EndDirectDebit

          #    - task: run-product-tests
          #      file: pay-endtoend-src/ci/tasks/run-tests.yml
          #      input_mapping: { repo: pay-endtoend-src }
          #      params:
          #        TEST_PROFILE: end2end-tagged
          #        GROUPS: uk.gov.pay.endtoend.categories.End2EndProducts
